backend/gncitizen/core/users/models.py, backend/gncitizen/core/users/routes.py, frontend/src/app/auth/auth.service.ts
New API url to delete personal datas for current logged user. 
All related fields (e.g. in observations table) are set to NULL (set NULL in cascade)
=> [RGPD] backend management of its own personal datas

backend/gncitizen/core/observations/routes.py
Les listes des observations sont maintenant ordonnées chronologiquement par date de création descendante, les plus récentes sont en haut de liste.
=> Order observations with timestamp_create (desc)

backend/gncitizen/utils/media.py, docs/devs/init_launch_frontend.rst, frontend/src/app/programs/observations/form/form.component.html, frontend/src/app/programs/observations/form/form.component.ts
hotfix for issue #72: 
- normalized UTC dates for observation submissions
- date validation fixes.
=> Hotfix pr93

frontend/src/app/home/home.component.html
Réintégration du bouton "Participer au programme" des blocs programmes de l'accueil.
Fixes #113
=> "Participer au programme" is back

.gitignore, data/ref_geo.sh, data/ref_geo.sql, frontend/src/app/core/topbar/topbar.component.html, frontend/src/app/core/topbar/topbar.component.ts
* Direct link to Backend BackOffice when logged as admin (vs iframe) 
* ref_geo populate scripts (execute this commands):
```sh
cd data
sudo ref_geo.sh
What is the db name?
my_db_name
```
=> BackOffice and ref_geo

frontend/src/app/about/fixed/fixed.component.html
Un petit patch pour une faute de frappe
=> fix character

backend/requirements.txt, backend/start_gunicorn.sh, docs/prod/index.rst
=> Doc review

backend/gncitizen/core/commons/admin.py, backend/gncitizen/core/commons/models.py, backend/gncitizen/core/commons/routes.py, data/migrations/v0.3.1_to_0.4.0.sql, frontend/src/app/core/topbar/topbar.component.ts, frontend/src/app/home/home.component.html, frontend/src/app/programs/default-program.guard.ts, frontend/src/app/programs/programs.component.html, frontend/src/app/programs/programs.models.ts
Flask-admin administration must now be secured with htpasswd in apache config, as mentionned in  #211
=> Improve flask-admin administration and update core models

docs/CHANGELOG.md
Première base de changelog, à relire, compléter par @lpofredc
=> Changelog 1.0.0

backend/requirements.txt, docs/CHANGELOG.md, frontend/src/app/auth/login/login.component.html, frontend/src/app/programs/sites/siteform/siteform.component.html, frontend/src/app/programs/sites/siteform/siteform.component.ts
* Last update broke site form validation when type is set by default when there is only one type site
* some TS code lint fixes (`const` vs `let`, typing)
* change envelop icon to `@` in login form
=> fix: can't valid site

backend/gncitizen/core/taxonomy/routes.py, backend/gncitizen/utils/taxonomy.py, backend/requirements-dev.txt, backend/start_gunicorn.sh, docs/authentification.rst, install/install_app.sh
fix: order api taxa list by french name
fix: update requirements.txt using:
- `poetry export --without-hashes > requirements.txt`
- `poetry export --without-hashes -D > requirements-dev.txt`
- but it's preferable to simply use `poetry install`
=> feat: some backend improvements

config/settings.ini.template, install/install_app.sh, install/install_taxhub.sh
**Goal:** Being able to install citizen when there is already a geonature and a taxhub instance installed and running
- Move all taxhub references from `install_app.sh` to `install_taxhub.sh`
- Add a condition to install taxhub based on install_taxhub variable in settings.ini
Closes #257
=> feat(install): Install citizen when geonature and taxhub are already installed

config/default_config.toml.template
This environment variable makes the backoffice display larger.
Which is convenient for larger screens
Closes #329
=> style(config): add FLASK_ADMIN_FLUID_LAYOUT

backend/gncitizen/core/observations/admin.py
Ajout de la possibilité d'exporter les observations au format CSV dans flask admin
Closes #344
=> feat/admin: add export obs

frontend/src/app/programs/observations/form/formValidators.ts
=> Fix form validation on negative longitude

backend/gncitizen/core/commons/admin.py, backend/gncitizen/core/commons/routes.py, backend/gncitizen/core/users/admin.py, backend/gncitizen/core/users/models.py, backend/gncitizen/core/users/routes.py
=> Merge and fix PR #371

backend/gncitizen/core/commons/models.py, backend/gncitizen/core/observations/routes.py, backend/gncitizen/core/sites/routes.py, data/migrations/v0.99.0_to_0.99.5.sql, frontend/src/app/programs/observations/modalflow/modalflow.component.ts, frontend/src/app/programs/observations/modalflow/steps/onboard/onboard.component.html, frontend/src/app/programs/observations/modalflow/steps/onboard/onboard.component.ts, frontend/src/app/programs/observations/obs.component.html, frontend/src/app/programs/programs.models.ts, frontend/src/app/programs/sites/modalflow/modalflow.component.ts, frontend/src/app/programs/sites/sites.component.html
Cette modification permet de forcer l'inscription de l'utilisateur si le programme sélectionné l'exige.
**Principales modifications:**
- Ajout d'un champ de type boolean sur le programme pour savoir si l'inscription est obligatoire pour contribuer à celui-ci.
- Ajout d'une condition en fonction de la variable dans onboard.component.ts pour empêcher l'utilisateur de continuer sans être connecté
- A l'ajout d'une observation ou d'un site, vérification de l'utilisateur dans l'API si le champs registration_required du programme est sur true
=> Inscription obligatoire pour la contribution à certains programmes

config/settings.ini.template
As suggested in https://github.com/PnX-SI/GeoNature-citizen/issues/352
I also updated TaxHub latest version to install, not sure it is compatible ?
=> Update and clarify settings.ini.template

docs/installation.rst, install/copy_config.sh, install/install_app.sh
Quelques petits correctifs pour une installation fonctionnelle de la branche dev (v1.0.0)
=> Patch dev v1.0.0

frontend/src/app/programs/base/detail/detail.component.html
Fix date format detail component
fix #398
=> Fix_issue_398

backend/gncitizen/__init__.py, backend/gncitizen/core/commons/models.py, backend/gncitizen/core/observations/admin.py, backend/gncitizen/core/sites/admin.py, backend/gncitizen/core/sites/models.py, backend/gncitizen/core/sites/routes.py, backend/gncitizen/utils/geo.py, backend/gncitizen/utils/helpers.py
Add site and visit management on backoffice
fix #399
=> Fix_issue_399

backend/Dockerfile, backend/gncitizen/utils/taxonomy.py, docker-compose.dev.yml, docker-compose.prod.yml, docker-compose.yml, frontend/Dockerfile, frontend/src/app/programs/observations/detail/detail.component.ts, frontend/src/app/programs/observations/form/form.component.ts, frontend/src/app/programs/programs.models.ts, frontend/src/app/programs/sites/detail/detail.component.ts, frontend/src/app/programs/sites/siteform/siteform.component.css, frontend/src/app/programs/sites/siteform/siteform.component.html, frontend/src/app/programs/sites/siteform/siteform.component.ts, frontend/src/conf/map.config.ts.template
merge #415 and fix some little things.
=> Fix and merge #415

install/apache/gncitizen.conf
Voir issue: #434 
Closes: #434
Reviewed-by: andriacap
=> fix: url redirection backoffice admin

backend/gncitizen/core/commons/routes.py, frontend/src/app/home/home.component.html, frontend/src/i18n/messages.de.xlf, frontend/src/i18n/messages.en.xlf, frontend/src/i18n/messages.fr.xlf, frontend/src/i18n/messages.xlf
Ajout de la stat "Nombre de sites" sur la page d'accueil.
Closes: #437 
Reviewed-by: andriac
=> feat: add stats home for nb site

backend/gncitizen/core/users/models.py, backend/gncitizen/core/users/routes.py, frontend/src/app/auth/register/register.component.html
This PR corrects password hashing when a new account is created, giving priority to hashing by trigger on the model (event listener).
Fix #445
=> Fix password hash on registration
